### PR TITLE
Just added imdb rating

### PR DESCRIPTION
**Pull request by ManyCoding**
Could you explain why it fails on tests?

### CODE REVIEW

**Comment by ManyCoding** [comment]
Could you explain why it fails on tests?

**Comment by jvanbaarsen** [comment]
Hm, I think because of invalid fixtures. I really need to fix those. Also if you want, I'll be accepting PR's for this!

**Comment by ManyCoding** [comment]
I fixed some, but I'm not sure what I'm doing. Could you explain more?

**Comment by jvanbaarsen** [comment]
@ManyCoding I finally got some time to take a look at your code :) When I pulled from master and ran the tests they al where green. I'll give you're code a shot now, ok?

**Comment by jvanbaarsen** [comment]
@ManyCoding Ah, when I updated the gems (did a re-install) I get the same errors as you have. I'll fix those in master for you!

**Comment by jvanbaarsen** [comment]
@ManyCoding I fixed the failing tests in master, if you rebase with master you can probably continue to work on your feature without problems!

**Pull request closed without merging**
