### PR TITLE
Added imdb rating

### PR DESCRIPTION
**Pull request by ManyCoding**
Let's see now. I'm totally confused with my fork after rebase, so I recreated it.

### CODE REVIEW

**Comment by jvanbaarsen** [comment]
Nice! Seems to work :) Let me know when you're ready so I can merge!

**Comment by ManyCoding** [comment]
Sure, go ahead.
By the way, last time under rebase you meant I should have pulled update from your original repo on my master and then rebased my branch with changes onto my master?

**Comment by jvanbaarsen** [comment]
Well, yeah you should have updated the master branch, then go to your feature branch and run the command: `git rebase master` :)

**Comment by ManyCoding** [comment]
Next time I will introduce features in separate branches instead in master )

**Comment by jvanbaarsen** [comment]
haha :) Yeah its a good practice in general :D

**Pull request merged**
